name: API Tests 

on: 
  push:
    branches: [ main ] 

jobs:   
    test:     
        runs-on: ubuntu-latest      
        steps:       
            - uses: actions/checkout@v4        
                        
            - name: Setup Node.js         
                uses: actions/setup-node@v4         
                with:           
                    node-version: '20'        
            - name: Install Bruno CLI         
                run: npm install -g @usebruno/cli
            - name: Run tests without Mock     
                run: echo "Listeing test files..."
                       ls -la user-tests/post-tests/ | | echo "No tests found"
                       echo "Tests will br added later"